import React, { useEffect, useState } from 'react';
import { AlertCircle, Check, CheckCircle2, HelpCircle, Loader2, Megaphone, Plus, Sparkles, Target, AlertTriangle } from 'lucide-react';
import DashboardLayout from '../../../components/layout/DashboardLayout';
import { addGtmTaskToRoadmap, generateGtmStrategy, getOrCreateGtmStrategy, listIdeas, saveGtmSetup, toggleFirst100Task, updateChannelStatus } from '../../../lib/api';

const PRODUCT_TYPES = ['SaaS', 'Mobile App', 'Hardware + Software', 'Consumer Product', 'B2B', 'Marketplace', 'Other'];
const STAGES = ['Idea', 'Prototype', 'MVP', 'Beta', 'Ready to Launch'];
const statuses = ['untested', 'testing', 'keep', 'drop'];
const statusStyles: Record<string, string> = { untested: 'bg-slate-100 text-slate-600', testing: 'bg-blue-100 text-blue-700', keep: 'bg-green-100 text-green-700', drop: 'bg-red-100 text-red-700' };

function AddToRoadmap({ ideaId, title }: { ideaId: string; title: string }) {
  const [added, setAdded] = useState(false); const [busy, setBusy] = useState(false);
  const add = async () => { setBusy(true); try { await addGtmTaskToRoadmap(ideaId, title); setAdded(true); } finally { setBusy(false); } };
  return added ? <span className="flex items-center gap-1 text-xs text-green-600"><Check className="w-3 h-3" />Added</span> : <button disabled={busy} onClick={add} className="flex items-center gap-1 text-xs text-primary-600 hover:underline disabled:opacity-50"><Plus className="w-3 h-3" />Add to roadmap</button>;
}

export default function GtmStrategyPage() {
  const [ideas, setIdeas] = useState<any[]>([]); const [ideaId, setIdeaId] = useState(''); const [row, setRow] = useState<any>(null);
  const [form, setForm] = useState<Record<string, string>>({ productType: '', currentStage: '', targetMarket: '', launchLocation: '', initialBudget: '', launchGoal: '' });
  const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState('');
  const strategy = row?.strategy;
  useEffect(() => { listIdeas().then((data) => { setIdeas(data || []); if (data?.[0]) setIdeaId(data[0].id); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!ideaId) return; setRow(null); getOrCreateGtmStrategy(ideaId).then((data) => { setRow(data); setForm((old) => ({ ...old, ...(data.setup || {}) })); }).catch((e) => setError(e.message)); }, [ideaId]);
  const generate = async () => { if (!row) return; setGenerating(true); setError(''); try { await saveGtmSetup(row.id, form); const generated = await generateGtmStrategy(row.id, ideaId, form); setRow({ ...row, setup: form, strategy: generated }); } catch (e: any) { setError(e.message || 'Could not generate a strategy.'); } finally { setGenerating(false); } };
  const changeStatus = async (index: number, status: string) => { try { const updated = await updateChannelStatus(row.id, strategy, index, status); setRow({ ...row, strategy: updated }); } catch (e: any) { setError(e.message); } };
  const toggle = async (phase: number, task: number) => { try { const updated = await toggleFirst100Task(row.id, strategy, phase, task); setRow({ ...row, strategy: updated }); } catch (e: any) { setError(e.message); } };
  const set = (key: string, value: string) => setForm({ ...form, [key]: value });
  if (loading) return <DashboardLayout><div className="flex justify-center py-24"><Loader2 className="animate-spin text-primary-600" /></div></DashboardLayout>;
  if (!ideas.length) return <DashboardLayout><div className="py-24 text-center"><h1 className="text-xl font-bold">No ideas yet</h1><p className="mt-2 text-slate-500">Add an idea first, then build its GTM strategy.</p></div></DashboardLayout>;
  return <DashboardLayout><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold font-display text-slate-900 sm:text-3xl">🚀 Go-To-Market Strategy</h1><p className="mt-1 text-slate-500">Turn strategy into real roadmap tasks—not just another document.</p></div><select value={ideaId} onChange={(e) => setIdeaId(e.target.value)} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm">{ideas.map((idea) => <option key={idea.id} value={idea.id}>{idea.title}</option>)}</select></div>
    {error && <div className="mb-6 flex gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="w-4 shrink-0" />{error}</div>}
    <section className="mb-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold">Build your Go-To-Market Strategy</h2><div className="mb-4 grid gap-4 md:grid-cols-2">
      <Field label="Product type"><select value={form.productType} onChange={(e) => set('productType', e.target.value)}><option value="">Select…</option>{PRODUCT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Current stage"><select value={form.currentStage} onChange={(e) => set('currentStage', e.target.value)}><option value="">Select…</option>{STAGES.map((item) => <option key={item}>{item}</option>)}</select></Field>
      <Field label="Target market"><input value={form.targetMarket} onChange={(e) => set('targetMarket', e.target.value)} placeholder="e.g. College students" /></Field><Field label="Launch location"><input value={form.launchLocation} onChange={(e) => set('launchLocation', e.target.value)} placeholder="e.g. Pondicherry" /></Field><Field label="Initial budget"><input value={form.initialBudget} onChange={(e) => set('initialBudget', e.target.value)} placeholder="e.g. ₹50,000" /></Field><Field label="Launch goal"><input value={form.launchGoal} onChange={(e) => set('launchGoal', e.target.value)} placeholder="e.g. 100 users in 30 days" /></Field>
    </div><button disabled={generating || !row} onClick={generate} className="flex items-center gap-2 rounded-lg bg-primary-600 px-5 py-2.5 font-medium text-white disabled:opacity-50">{generating ? <Loader2 className="w-4 animate-spin" /> : <Sparkles className="w-4" />}{generating ? 'Generating…' : strategy ? 'Regenerate GTM Strategy' : 'Generate GTM Strategy'}</button></section>
    {strategy && <div className="space-y-8"><Card title="Target Customer" icon={<Target className="w-4" />}><p className="mb-3 text-sm text-slate-700">{strategy.targetCustomer?.primary}</p><div className="flex flex-wrap gap-2">{strategy.targetCustomer?.earlyAdopters?.map((item: string) => <span key={item} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{item}</span>)}</div></Card>
      <Card title="Positioning"><p className="mb-3 text-sm font-medium">{strategy.positioning?.statement}</p><div className="grid gap-4 text-sm md:grid-cols-2"><div><Label>Alternatives</Label><ul className="list-inside list-disc text-slate-600">{strategy.positioning?.alternatives?.map((item: string) => <li key={item}>{item}</li>)}</ul></div><div><Label>Differentiation</Label><p className="text-slate-600">{strategy.positioning?.differentiation}</p></div></div></Card>
      <Card title="Messaging" icon={<Megaphone className="w-4" />}>{[['One-liner', strategy.messaging?.oneLiner], ['Short pitch', strategy.messaging?.shortPitch], ['Landing headline', strategy.messaging?.landingHeadline], ['Social message', strategy.messaging?.socialMessage]].map(([label, text]) => <div key={label as string} className="mb-3 text-sm"><Label>{label as string}</Label><p>{text as string}</p></div>)}</Card>
      <Card title="Channel Experiments"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{strategy.channels?.map((channel: any, index: number) => <div key={channel.name} className="rounded-lg border border-slate-200 bg-slate-50 p-4"><div className="mb-2 flex justify-between"><b className="text-sm">{channel.name}</b><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${statusStyles[channel.status] || statusStyles.untested}`}>{channel.status}</span></div><p className="mb-3 text-xs text-slate-500">Cost: {channel.cost} · Reach: {channel.reach} · Confidence: {channel.confidence}</p><select value={channel.status} onChange={(e) => changeStatus(index, e.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div>)}</div></Card>
      <Card title="First 100 Customers"><div className="space-y-4">{strategy.first100?.map((phase: any, pi: number) => <div key={phase.phase} className="rounded-lg border border-slate-100 p-4"><div className="mb-2 flex justify-between"><b className="text-sm">{phase.phase}</b><span className="text-xs text-slate-500">{phase.range}</span></div>{phase.tasks?.map((task: any, ti: number) => <div key={task.title} className="flex items-center justify-between gap-2 py-1"><label className="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={task.done} onChange={() => toggle(pi, ti)} /><span className={task.done ? 'text-slate-400 line-through' : ''}>{task.title}</span></label><AddToRoadmap ideaId={ideaId} title={task.title} /></div>)}</div>)}</div></Card>
      <Card title="30-Day Launch Timeline"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{strategy.launchTimeline?.map((week: any) => <div key={week.week} className="rounded-lg border border-slate-100 p-3"><b className="text-xs text-primary-600">{week.week}</b>{week.tasks?.map((task: string) => <div key={task} className="mt-2 text-xs text-slate-700"><p>{task}</p><AddToRoadmap ideaId={ideaId} title={task} /></div>)}</div>)}</div></Card>
      <div className="grid gap-4 md:grid-cols-3"><Risk title="Strong" values={strategy.riskAnalysis?.strong} style="green" icon={<CheckCircle2 className="w-4" />} /><Risk title="Uncertain" values={strategy.riskAnalysis?.uncertain} style="amber" icon={<HelpCircle className="w-4" />} /><Risk title="Critical" values={strategy.riskAnalysis?.critical} style="red" icon={<AlertTriangle className="w-4" />} /></div>
    </div>}</DashboardLayout>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-slate-600">{label}<span className="mt-1 block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-200 [&_input]:p-2.5 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:p-2.5">{children}</span></label>; }
function Label({ children }: { children: React.ReactNode }) { return <span className="block text-xs font-bold uppercase text-slate-500">{children}</span>; }
function Card({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 flex items-center gap-2 font-bold">{icon}{title}</h2>{children}</section>; }
function Risk({ title, values, style, icon }: { title: string; values?: string[]; style: 'green' | 'amber' | 'red'; icon: React.ReactNode }) { const styles: Record<string, string> = { green: 'border-green-100 bg-green-50 text-green-900', amber: 'border-amber-100 bg-amber-50 text-amber-900', red: 'border-red-100 bg-red-50 text-red-900' }; return <div className={`rounded-xl border p-4 ${styles[style]}`}><h3 className="mb-3 flex items-center gap-2 text-sm font-bold">{icon}{title}</h3><ul className="space-y-1 text-sm">{values?.map((value) => <li key={value}>• {value}</li>)}</ul></div>; }
